# Generated by Django 5.1.4 on 2026-06-15 06:29

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('bookings', '0003_booking_proforma_invoice_container_stuffed_at_and_more'),
        ('master_data', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BillOfLading',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bl_number', models.CharField(max_length=50, unique=True)),
                ('bl_type', models.CharField(choices=[('LINE', 'Line BL'), ('DIRECT', 'Direct BL')], max_length=10)),
                ('status', models.CharField(choices=[('DRAFT', 'Draft'), ('SUBMITTED', 'Submitted'), ('RELEASED', 'Released')], default='DRAFT', max_length=20)),
                ('container_number', models.CharField(max_length=50)),
                ('vessel_name', models.CharField(max_length=255)),
                ('voyage_number', models.CharField(max_length=100)),
                ('notify_party', models.TextField(blank=True)),
                ('cargo_description', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('booking', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='bills_of_lading', to='bookings.booking')),
                ('consignee', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='bills_of_lading', to='master_data.consignee')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='bills_of_lading_created', to=settings.AUTH_USER_MODEL)),
                ('shipper', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='bills_of_lading', to='master_data.shipper')),
            ],
            options={
                'verbose_name': 'Bill of Lading',
                'verbose_name_plural': 'Bills of Lading',
                'ordering': ['-created_at'],
            },
        ),
    ]
