from django.conf import settings
from django.db import models


class Alert(models.Model):
    """Persistent alert records generated by automated checks."""

    class AlertType(models.TextChoices):
        MISSING_BL = 'MISSING_BL', 'Missing BL'
        PENDING_BL = 'PENDING_BL', 'Pending BL'
        PAYMENT_OVERDUE = 'PAYMENT_OVERDUE', 'Payment Overdue'
        SHIPMENT_DELAY = 'SHIPMENT_DELAY', 'Shipment Delay'

    alert_type = models.CharField(max_length=30, choices=AlertType.choices)
    message = models.TextField()
    related_object_id = models.PositiveIntegerField(null=True, blank=True)
    related_object_type = models.CharField(max_length=50, blank=True)
    is_read = models.BooleanField(default=False)
    is_resolved = models.BooleanField(default=False)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    class Meta:
        ordering = ['-created_at']
        indexes = [
            models.Index(fields=['alert_type', 'is_resolved'], name='idx_alert_type_resolved'),
            models.Index(fields=['related_object_id', 'related_object_type'], name='idx_alert_related'),
        ]

    def __str__(self):
        return f"[{self.get_alert_type_display()}] {self.message[:50]}"
