# Generated by Django 5.1.4 on 2026-06-22 07:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Alert',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('alert_type', models.CharField(choices=[('MISSING_BL', 'Missing BL'), ('PENDING_BL', 'Pending BL'), ('PAYMENT_OVERDUE', 'Payment Overdue'), ('SHIPMENT_DELAY', 'Shipment Delay')], max_length=30)),
                ('message', models.TextField()),
                ('related_object_id', models.PositiveIntegerField(blank=True, null=True)),
                ('related_object_type', models.CharField(blank=True, max_length=50)),
                ('is_read', models.BooleanField(default=False)),
                ('is_resolved', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['alert_type', 'is_resolved'], name='idx_alert_type_resolved'), models.Index(fields=['related_object_id', 'related_object_type'], name='idx_alert_related')],
            },
        ),
    ]
