# Generated by Django 5.1.4 on 2026-06-15 06:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='StockItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(max_length=255, unique=True)),
                ('available_stock', models.PositiveIntegerField(default=0)),
                ('reserved_stock', models.PositiveIntegerField(default=0)),
                ('shipped_stock', models.PositiveIntegerField(default=0)),
                ('unit', models.CharField(default='units', max_length=50)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'constraints': [models.CheckConstraint(condition=models.Q(('available_stock__gte', 0)), name='available_stock_non_negative'), models.CheckConstraint(condition=models.Q(('reserved_stock__gte', 0)), name='reserved_stock_non_negative'), models.CheckConstraint(condition=models.Q(('shipped_stock__gte', 0)), name='shipped_stock_non_negative')],
            },
        ),
    ]
