# Generated by Django 5.1.4 on 2026-06-22 11:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stockitem',
            name='unit',
            field=models.CharField(choices=[('units', 'Units'), ('kg', 'Kilograms (kg)'), ('bags', 'Bags'), ('tonnes', 'Tonnes'), ('litres', 'Litres'), ('meters', 'Meters'), ('pieces', 'Pieces'), ('boxes', 'Boxes'), ('cartons', 'Cartons'), ('pallets', 'Pallets')], default='units', max_length=50),
        ),
    ]
