# Generated by Django 5.1.4 on 2026-06-14 15:56

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('master_data', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('job_number', models.CharField(editable=False, max_length=20, unique=True)),
                ('booking_no', models.CharField(blank=True, max_length=50)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('DO_BOOKING_EDIT', 'DO-Booking Edit'), ('COMPLETED', 'Completed')], default='PENDING', max_length=20)),
                ('booking_date', models.DateField()),
                ('booking_validity_date', models.DateField()),
                ('forwarding_window_start', models.DateField()),
                ('forwarding_window_end', models.DateField()),
                ('cargo_type', models.CharField(choices=[('FCL', 'Full Container Load'), ('LCL', 'Less than Container Load')], max_length=3)),
                ('shipment_type', models.CharField(max_length=50)),
                ('stuffing_type', models.CharField(max_length=50)),
                ('voyage', models.CharField(blank=True, max_length=100)),
                ('etd_pol', models.DateTimeField(blank=True, null=True)),
                ('eta_destination', models.DateTimeField(blank=True, null=True)),
                ('si_cut_off', models.DateTimeField(blank=True, null=True)),
                ('vgm_cut_off', models.DateTimeField(blank=True, null=True)),
                ('sb_cut_off', models.DateTimeField(blank=True, null=True)),
                ('gate_cut_off', models.DateTimeField(blank=True, null=True)),
                ('clearance_point', models.CharField(blank=True, max_length=255)),
                ('stuffing_point', models.CharField(blank=True, max_length=255)),
                ('expected_stuffing_date', models.DateField(blank=True, null=True)),
                ('is_icd_hand_over', models.BooleanField(default=False)),
                ('transport_involved', models.BooleanField(default=False)),
                ('clearance_involved', models.BooleanField(default=False)),
                ('buyer', models.CharField(blank=True, max_length=255)),
                ('quotation_no', models.CharField(blank=True, max_length=50)),
                ('docs_holder', models.CharField(blank=True, max_length=255)),
                ('po_no', models.CharField(blank=True, max_length=100)),
                ('shipper_invoice_no', models.CharField(blank=True, max_length=100)),
                ('hbl_no', models.CharField(blank=True, max_length=50)),
                ('mbl_no', models.CharField(blank=True, max_length=50)),
                ('hbl_freight_terms', models.CharField(blank=True, choices=[('PREPAID', 'Prepaid'), ('COLLECT', 'Collect')], max_length=10)),
                ('mbl_freight_terms', models.CharField(blank=True, choices=[('PREPAID', 'Prepaid'), ('COLLECT', 'Collect')], max_length=10)),
                ('bl_type', models.CharField(blank=True, max_length=50)),
                ('mbl_type', models.CharField(blank=True, max_length=50)),
                ('certificates', models.JSONField(blank=True, default=list)),
                ('is_haz', models.BooleanField(default=False)),
                ('haz_class', models.CharField(blank=True, max_length=50)),
                ('haz_uin', models.CharField(blank=True, max_length=100)),
                ('haz_group', models.CharField(blank=True, max_length=50)),
                ('remarks', models.TextField(blank=True, max_length=2000)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='bookings', to='master_data.client')),
                ('commodity', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='bookings', to='master_data.commodity')),
                ('consignee', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='bookings', to='master_data.consignee')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='bookings_created', to=settings.AUTH_USER_MODEL)),
                ('fpd', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='bookings_as_fpd', to='master_data.port')),
                ('marketing_person', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='bookings', to='master_data.marketingperson')),
                ('nvocc_forwarder', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='bookings', to='master_data.forwarder')),
                ('pod', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='bookings_as_pod', to='master_data.port')),
                ('pol', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='bookings_as_pol', to='master_data.port')),
                ('por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='bookings_as_por', to='master_data.port')),
                ('shipper', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='bookings', to='master_data.shipper')),
                ('shipping_line', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='bookings', to='master_data.shippingline')),
                ('transporter', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='bookings', to='master_data.transporter')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='bookings_updated', to=settings.AUTH_USER_MODEL)),
                ('vessel', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='bookings', to='master_data.vessel')),
            ],
            options={
                'ordering': ['-booking_date'],
            },
        ),
        migrations.CreateModel(
            name='BookingStatusHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('previous_status', models.CharField(choices=[('PENDING', 'Pending'), ('DO_BOOKING_EDIT', 'DO-Booking Edit'), ('COMPLETED', 'Completed')], max_length=20)),
                ('new_status', models.CharField(choices=[('PENDING', 'Pending'), ('DO_BOOKING_EDIT', 'DO-Booking Edit'), ('COMPLETED', 'Completed')], max_length=20)),
                ('changed_at', models.DateTimeField(auto_now_add=True)),
                ('booking', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='status_history', to='bookings.booking')),
                ('changed_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-changed_at'],
            },
        ),
        migrations.CreateModel(
            name='CommunicationLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email_type', models.CharField(max_length=50)),
                ('recipients', models.JSONField()),
                ('sent_at', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(max_length=20)),
                ('error_message', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('booking', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='communication_logs', to='bookings.booking')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Container',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('container_size', models.CharField(choices=[('20FT', '20ft'), ('40FT', '40ft'), ('40FT_HC', '40ft HC'), ('45FT', '45ft')], max_length=10)),
                ('container_count', models.PositiveIntegerField()),
                ('container_no', models.CharField(blank=True, max_length=20)),
                ('seal_no', models.CharField(blank=True, max_length=20)),
                ('booking', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='containers', to='bookings.booking')),
                ('container_type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='containers', to='master_data.containertype')),
            ],
        ),
        migrations.CreateModel(
            name='TranshipmentLeg',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sequence', models.PositiveSmallIntegerField()),
                ('eta', models.DateTimeField()),
                ('connecting_vessel_voyage', models.CharField(max_length=200)),
                ('etd', models.DateTimeField()),
                ('booking', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transhipment_legs', to='bookings.booking')),
                ('port', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='transhipment_legs', to='master_data.port')),
            ],
            options={
                'ordering': ['sequence'],
            },
        ),
        migrations.AddIndex(
            model_name='booking',
            index=models.Index(fields=['booking_date'], name='idx_booking_date'),
        ),
        migrations.AddIndex(
            model_name='booking',
            index=models.Index(fields=['status'], name='idx_status'),
        ),
        migrations.AddIndex(
            model_name='booking',
            index=models.Index(fields=['client'], name='idx_client'),
        ),
        migrations.AddIndex(
            model_name='booking',
            index=models.Index(fields=['shipping_line'], name='idx_shipping_line'),
        ),
        migrations.AddIndex(
            model_name='booking',
            index=models.Index(fields=['etd_pol'], name='idx_etd_pol'),
        ),
        migrations.AddIndex(
            model_name='booking',
            index=models.Index(fields=['job_number'], name='idx_job_number'),
        ),
        migrations.AddIndex(
            model_name='booking',
            index=models.Index(fields=['booking_no'], name='idx_booking_no'),
        ),
        migrations.AddIndex(
            model_name='booking',
            index=models.Index(fields=['hbl_no'], name='idx_hbl_no'),
        ),
        migrations.AddIndex(
            model_name='booking',
            index=models.Index(fields=['mbl_no'], name='idx_mbl_no'),
        ),
        migrations.AddConstraint(
            model_name='container',
            constraint=models.CheckConstraint(condition=models.Q(('container_count__gte', 1)), name='container_count_positive'),
        ),
        migrations.AddConstraint(
            model_name='transhipmentleg',
            constraint=models.CheckConstraint(condition=models.Q(('sequence__lte', 4)), name='max_four_legs'),
        ),
        migrations.AddConstraint(
            model_name='transhipmentleg',
            constraint=models.CheckConstraint(condition=models.Q(('etd__gt', models.F('eta'))), name='etd_after_eta'),
        ),
        migrations.AlterUniqueTogether(
            name='transhipmentleg',
            unique_together={('booking', 'sequence')},
        ),
    ]
