# Generated by Django 5.1.4 on 2026-06-15 06:15

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0002_create_job_number_sequence'),
        ('proforma', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='proforma_invoice',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bookings', to='proforma.proformainvoice'),
        ),
        migrations.AddField(
            model_name='container',
            name='stuffed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='container',
            name='stuffed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='stuffed_containers', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='container',
            name='stuffing_status',
            field=models.CharField(choices=[('PENDING', 'Pending'), ('STUFFED', 'Stuffed')], default='PENDING', max_length=10),
        ),
        migrations.AlterField(
            model_name='booking',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Pending'), ('BOOKED', 'Booked'), ('STUFFING', 'Stuffing'), ('SHIPPED', 'Shipped'), ('COMPLETED', 'Completed')], default='PENDING', max_length=20),
        ),
        migrations.AlterField(
            model_name='bookingstatushistory',
            name='new_status',
            field=models.CharField(choices=[('PENDING', 'Pending'), ('BOOKED', 'Booked'), ('STUFFING', 'Stuffing'), ('SHIPPED', 'Shipped'), ('COMPLETED', 'Completed')], max_length=20),
        ),
        migrations.AlterField(
            model_name='bookingstatushistory',
            name='previous_status',
            field=models.CharField(choices=[('PENDING', 'Pending'), ('BOOKED', 'Booked'), ('STUFFING', 'Stuffing'), ('SHIPPED', 'Shipped'), ('COMPLETED', 'Completed')], max_length=20),
        ),
    ]
